# -*- coding: utf-8 -*-
#
# This file is part of Invenio.
# Copyright (C) 2016 CERN.
#
# Invenio is free software; you can redistribute it
# and/or modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation; either version 2 of the
# License, or (at your option) any later version.
#
# Invenio is distributed in the hope that it will be
# useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Invenio; if not, write to the
# Free Software Foundation, Inc., 59 Temple Place, Suite 330, Boston,
# MA 02111-1307, USA.
#
# In applying this license, CERN does not
# waive the privileges and immunities granted to it by virtue of its status
# as an Intergovernmental Organization or submit itself to any jurisdiction.


notifications:
  email: false

sudo: false

language: python

cache:
  directories:
    - $HOME/.cache/pip

services:
  - elasticsearch
  - redis
  - rabbitmq

env:
  - REQUIREMENTS=lowest BROKER_URL=redis://localhost:6379/0
  - REQUIREMENTS=lowest BROKER_URL=amqp://localhost:5672//
  - REQUIREMENTS=release BROKER_URL=redis://localhost:6379/0
  - REQUIREMENTS=release BROKER_URL=amqp://localhost:5672//
  - REQUIREMENTS=devel BROKER_URL=redis://localhost:6379/0
  - REQUIREMENTS=devel BROKER_URL=amqp://localhost:5672//

python:
  - "2.7"
  - "3.5"
  - "pypy"

matrix:
  allow_failures:
    - python: pypy

before_install:
  - "travis_retry pip install --upgrade pip setuptools py"
  - "travis_retry pip install twine wheel coveralls requirements-builder"
  - "requirements-builder --level=min setup.py > .travis-lowest-requirements.txt"
  - "requirements-builder --level=pypi setup.py > .travis-release-requirements.txt"
  - "requirements-builder --level=dev --req requirements-devel.txt setup.py > .travis-devel-requirements.txt"

install:
  - "travis_retry pip install -r .travis-${REQUIREMENTS}-requirements.txt"
  - "travis_retry pip install -e .[all]"

script:
  - "./run-tests.sh"

after_success:
  - coveralls

deploy:
  provider: pypi
  user: jirikuncar
  password:
    secure: RiFRV2gRaV/7MLELON7vWdfP4wPJDzYNm/+LmbW9rshXJ3IbzstomoNN+QEPvPfaiFs8dKwwo2r7vWUCgGedTY3Rksi2+iSMojOb5VfQJWM+Gy8wP6OdzM8NmjRyYxluWEzJtUY1cyU/ss2M+iqGpZQLdQpTWZ8E+SHpznFP5dFt/MVHUcsW8TTToSK4gJtmREmCxnYG05jE8nS0othg9Qf6LvmaLkdMGNNMcoe2qcmmEWDApjUhYGjF1qHt1ScVukVUQGP8mhV+3086ndASx/Sl5hwbQHm1sJS9rjOhRGqXZvnaxZ6RyDlNNXo+PGeKLHD3ErYBIhPiXY49oLeqlo8Sm5iOKsif8Gi7eK9mXGWrEmXfsvabWlcsqUKdjQYaC5RHCcmAXgQ3yGY3INTRIrmnYhWzN/o1XBESwFUxqlSrANobMZPdHwt2JZJHMJL5GRB8msqsw3Pfq6KZ7Gv4xK/FwK5GGMwSBBhPk2/ewXlvbbZqgwGJueEFSYW8oSoobjViHLoB1TJMbL5gU5hsAezQgg8FCzqiNwx1108HW6GW4KNgAKTnXVAjyS+VUARe/HE9j6C/gK9vJbpPryHsVyLv33DCiFG2jDCrw9scq2H5LU4gtps1bBKfWtEkVOGsj3Hdcbi4C9HVwKpazoiaH38th0q47rpcRLkbZGtOwdQ=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: inveniosoftware/invenio-indexer
